import Menu from "./Componentes/Menu";
import Registro from "./registro/page";
import RodaPe from "./Componentes/RodaPe";
import Local from "./localizacao/page";
import Map from "./Componentes/Map";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Menu/>
        <hr/>
    {children}
    <hr/>
      <RodaPe/>
      </body>
       </html>
  )
}
